Solve permission denied error for schema public on pgAdmin 4 postgres
With PostgreSQL 15 and onwards, there has been a change in the way table creation permissions are handled for users. Not directly related to pgAdmin 4, but I think people may run into this.

Normally, after allowing a user to CREATE tables within a database, you didn't have to specifically define that they had the permission to do that within a SCHEMA, since public would be the default one.

With PostgreSQL 15, this has changed (https://www.postgresql.org/about/news/postgresql-15-released-2526)

PostgreSQL 15 also revokes the CREATE permission from all users except a database owner from the public (or default) schema.

Error message:
ERROR: permission denied for schema public

Above error occurred while installing Alfresco using ZIP installer using postgres version 17.